### ISSUE TITLE
not getting this package from npm install

### ISSUE THREAD

**Issue by tandibar** [wix/protractor-helpers#29]
If i do `npm install --save-dev protractor-helpers` like described in docs i get a very different version of protractor-helpers (https://www.npmjs.com/package/protractor-helpers).
This is very confusing as installation just works but i cannot use any of your helper methods.

How can i get your package installed via npm?

**Comment by gilamran** [comment]
We are aware of this issue, and we've contacted the owner of the old package (protractor-helpers).
For now, you can use protractor_helpers (It might change in the near future)

**Comment by tandibar** [comment]
Ok, cool. Thx for updating the readme.

**Comment by gilamran** [comment]
I'm happy to say that we got the protractor-helpers npm package name :-) you can now use it. (As noted in the README)

**Comment by tandibar** [comment]
Perfekt! Congratulations :smile:
