### ISSUE TITLE
ETIMEDOUT trying to download dependencies of this package

### ISSUE THREAD

**Issue by evankleist** [wix/protractor-helpers#50]
All of our builds started failing today with ETIMEDOUT while trying to download dependencies from repo.dev.wixpress.com. I tracked it down to protractor-helpers which is causing the problems

`
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/has-ansi/-/has-ansi-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.121.205:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/concat-map/-/concat-map-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.121.205:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/has-color/-/has-color-0.1.7.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.123.179:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/connect/-/connect-3.6.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.127.140:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/har-validator/-/har-validator-5.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.126.231:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/combined-stream/-/combined-stream-1.0.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.123.179:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/har-schema/-/har-schema-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.127.140:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/grunt-legacy-log-utils/-/grunt-legacy-log-utils-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.123.179:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/coffee-script/-/coffee-script-1.3.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.127.140:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/grunt-release/-/grunt-release-0.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.121.205:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/colors/-/colors-0.6.2.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.126.231:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/grunt-protractor-runner/-/grunt-protractor-runner-5.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.126.231:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/co/-/co-4.6.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.121.205:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/grunt-legacy-log/-/grunt-legacy-log-0.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 10.42.127.140:443
npm ERR! fetch failed https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/chalk/-/chalk-0.5.1.tgz
`

**Comment by ahmed-abdulmoniem** [comment]
Yes .. this is happening a lot right now

**Comment by Teamop** [comment]
Hi @mastertheblaster , I found that this package use npm-shrinkwrap.json to lock dependencies which refer to https://repo.dev.wixpress.com/artifactory, then it can be a problem for the outside users, cause npm-shrinkwrap.json is included when publishing. 
So if you just want to lock the dependencies for your own usage, I think you can try with package-lock.json which is automatically generated after npm@5.X, also this file won't be included when publishing, so that you can also have the benefit for locking dependencies for your own usage and also not forcing outside users to have the dependencies from Artifactory.
thanks

**Comment by mastertheblaster** [comment]
@Teamop should be fixed in version `1.1.472`. Removed `shrinkwrap` option.

**Comment by Teamop** [comment]
@mastertheblaster thanks
